USE [master]
GO

CREATE SERVER AUDIT [SQLAudit-Server-Login-Password-Change]
TO FILE 
(	FILEPATH = N'D:\'
	,MAXSIZE = 0 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE -- ON_FAILURE = { CONTINUE | SHUTDOWN | FAIL_OPERATION}
)
GO